# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 47b6d9a
_src_path: /Users/adrianlyjak/dev/template-workflow-data-extraction
project_name: test-proj
project_title: Test Project
