/* eslint-disable */
import type { JSONObject } from "@llamaindex/ui";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Hello = string;

export interface MySchema {
  hello: Hello;
  [k: string]: JSONObject;
}
